version: 2
jobs:
  build:
    branches:
        only: master
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          key: v1-dependencies-

      - run: 
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: build - gatsby 
          command: npm run build     

      - run: 
          name: Deploy To Production
          command: firebase deploy --token=$FIREBASE_TOKEN --non-interactive
